import type { Metadata } from 'next';
import GlobalStyles from '../../theme/global';
import StyledComponentsRegistry from '../../lib/registry';

export const metadata: Metadata = {
  title: 'Next App Toggle-like',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <GlobalStyles />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
